name: Fix
description: Request a bug fix to be completed
title: "fix: <title>"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: Describe the bug
      placeholder: |
        When I do something, I expect something to happen, but instead something else happens.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        Add any other context or screenshots about the bug here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Describe how to verify the bug is fixed
      placeholder: |
        GIVEN I am a user
        WHEN I do something
        THEN I expect something
    validations:
      required: true
  - type: input
    attributes:
      label: Story Points
      description: How many story points is this issue worth?
      placeholder: "e.g. 1, 2, 3"
    validations:
      required: false